apiVersion: v1
kind: Pod
metadata:
  name: kubernetes-demo-app
  labels:
    app.kubernetes.io/name: kubernetes-demo-app
spec:
  containers:
    - name: kubernetes-demo-app
      image: kubernetes-demo-app:latest
      env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
      imagePullPolicy: IfNotPresent
      ports:
        - protocol: TCP
          containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: kubernetes-demo-service
spec:
  selector:
    app.kubernetes.io/name: kubernetes-demo-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP