apiVersion: v1
kind: Pod
metadata:
  name: kubernetes-demo-app
  labels:
    app.kubernetes.io/name: kubernetes-demo-app
spec:
  containers:
    - name: kubernetes-demo-app
      image: 192.168.64.2/kubernetes-demo-app:latest
      ports:
        - protocol: TCP
          containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: kubernetes-demo-service
  labels:
    app.kubernetes.io/name: kubernetes-demo-app
spec:
  selector:
    app: kubernetes-demo-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: minimal-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: kubernetes-demo.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: kubernetes-demo-service
                port:
                  number: 80
