apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubernetes-demo-app
  labels:
    app.kubernetes.io/name: kubernetes-demo-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: kubernetes-demo-app
  template:
    metadata:
      labels:
        app.kubernetes.io/name: kubernetes-demo-app
    spec:
      containers:
        - name: kubernetes-demo-app
          image: kubernetes-demo-app:latest
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          imagePullPolicy: IfNotPresent
          ports:
            - protocol: TCP
              containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: kubernetes-demo-service-lb
spec:
  selector:
    app.kubernetes.io/name: kubernetes-demo-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer